### ISSUE TITLE
STORY: As a handler developer, I want to send my generated text segments to a translation service so that I can provide experiences in languages other than English.

### ISSUE THREAD

**Issue by notkaramel** [Shared-Reality-Lab/IMAGE-server#696]
## Description
As the translation service was implemented (#688), we will now integrate language support into handlers, starting with `photo-audio-handler` then other handlers.

## Tasks
> Tasks will be updated over the period of the sprint.
### `photo-audio-handler`
- [x] Adding language handling
- [x] Send segments to translation service
- [x] Send translated segments to TTS service
- [x] Create tests to ensure functionality of handler
- [ ] Test results on a variety of photos from IMAGE-test-graphics repo
- [x] Create pull request

## Features (for future sprints)
(?) Implement automated or manual switch to change language of IMAGE renderings

**Comment by notkaramel** [comment]
While the `photo-audio-handler` is under review, two new PRs were created as part of the story:
- Autour handler (Map): #717 
- High Charts handler (Chart): #718 

Improvement will continue to be made until the end of sprint to all integrations
