### ISSUE TITLE
STORY: As an IMAGE user, I want to be able to select an output language on the extension, so that I can experience IMAGE in my preferred language.

### ISSUE THREAD

**Issue by notkaramel** [Shared-Reality-Lab/IMAGE-server#724]
## Tasks
- [ ] Finalise the language selection handling design
- [ ] Create a UI element for language selection
- [ ] Test the functionality
