### ISSUE TITLE
EPIC: As a handler developer, I want accurate information about text in graphics beyond just the raw words, so that I can create more informative audio and Monarch experiences

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#846]
Our current OCR is cloud based, but has multiple issues such as spurious text found. So accuracy is an issue, and one of the main reasons why this is only available on our test server, and not in production.

Text in graphics is likely even more important in textbook diagrams than in photos, so is crucial to our current Monarch goals.

Beyond just the raw words we can find, text is likely also key to understanding the structure of diagrams. Bigger text is likely a heading or more important point. Different fonts may be used in different areas of a diagram. Angled or vertical text may be important since it may label an axis or help show the flow of steps in a process. #524 talks about this just for fonts, but there are probably many other aspects that would be useful if they can be captured.

So, this epic has multiple parts. First take:

- [ ] Get clean OCR results without spurious text found. This would allow us to deploy OCR quickly for existing experiences.
- [ ] Figure out what aspects of text we can capture (beyond bounding boxes, which we already have) that would be useful for making sense of textbook diagrams.
- [ ] Update OCR JSON schema to support this additional information in a structured way
- [ ] Determine if there is further processing that should be done to make sense of the interaction of text with other elements of the graphic. For example, the current system tries to associate text with objects found in a photo (e.g., a bottle that contains the text "cola"). This may or may not be applicable in a textbook diagram, but maybe there are other elements, e.g., text all aligned in the same direction may need to be tagged as related in some way.
- [ ] Implement further processing to create JSON output that captures all the relationships we can find, for use by handlers.
